### ISSUE TITLE
dark theme (example code)

### ISSUE THREAD

**Issue by atomGit** [hnakamur/FormatLink-Firefox#58]
for the options page...

```css
@-moz-document url("moz-extension://<INSERT EXTENSION ID>/options.html") {
    body {
        background-color: #272727;
        color: #ccc;
    }
    input[type="text"] {
        -moz-default-appearance: unset;
        background-color: #1f1f1f;
        color: #e7f874;
        text-rendering: unset;
    }
}
```

for the pop-up...

```css
@-moz-document url("moz-extension://<INSERT EXTENSION ID>/popup.html") {
    body {
        background: #242424;
        color: #d9d9d9;
        border: 2px solid gray;
    }
    #formatGroup {
        display: grid;
        min-width: 40em;
    }
}
```
